# -*- coding: utf-8 -*-
"""neuralnetworksformnist.ipynb 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fozTNRtwHM3umPVH6Fy6J6P3eKUa8RBr
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

transform = transforms.ToTensor()

train_data = datasets.MNIST(root="./data", train=True, download=True, transform=transform)
test_data = datasets.MNIST(root="./data", train=False, download=True, transform=transform)

train_loader = DataLoader(train_data, batch_size=64, shuffle=True)
test_loader = DataLoader(test_data, batch_size=64)

class SimpleNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = nn.Sequential(
            nn.Flatten(),          # 28x28 → 784
            nn.Linear(784, 128),
            nn.ReLU(),
            nn.Linear(128, 10)     # 10 classes
        )

    def forward(self, x):
        return self.model(x)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = SimpleNN().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

for epoch in range(3):
    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    print(f"Epoch {epoch+1} done")

torch.save(model.state_dict(), "model.pth") # save model weights

correct = 0
total = 0

model.eval()
with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        preds = torch.argmax(outputs, dim=1)

        total += labels.size(0)
        correct += (preds == labels).sum().item()

print("Accuracy:", 100 * correct / total)

import matplotlib.pyplot as plt

# Get a batch of test images and labels
dataiter = iter(test_loader)
images, labels = next(dataiter)

# Move to device
images, labels = images.to(device), labels.to(device)

# Make predictions
model.eval()
with torch.no_grad():
    outputs = model(images)
    preds = torch.argmax(outputs, dim=1)

# Display some images with predictions and true labels
fig = plt.figure(figsize=(10, 8))
for i in range(9):
    ax = fig.add_subplot(3, 3, i + 1, xticks=[], yticks=[])
    # Convert image to numpy array for displaying
    img = images[i].cpu().numpy().squeeze()
    ax.imshow(img, cmap='gray')
    ax.set_title(f"True: {labels[i].item()}\nPred: {preds[i].item()}",
                 color=("green" if preds[i] == labels[i] else "red"))
plt.tight_layout()
plt.show()

